import { Member } from '../types/attendance';

export const INITIAL_MEMBERS: Member[] = [
  { id: '1', name: '강규태', semesterCount: '', tier: '신입', attendances: { '26.9': '8, 15' } },
  { id: '2', name: '강동희', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '3', name: '김규백', semesterCount: '3+', tier: 'OB', attendances: { '26.9': '' } },
  { id: '4', name: '김남혁', semesterCount: '', tier: '신입', attendances: { '26.9': '8' } },
  { id: '5', name: '김도현', semesterCount: '', tier: '신입', attendances: { '26.9': '18' } },
  { id: '6', name: '김문영', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '7', name: '김민경', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '10, 11' } },
  { id: '8', name: '김민서', semesterCount: '3+', tier: 'OB', attendances: { '26.9': '' } },
  { id: '9', name: '김민영', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '8, 15' } },
  { id: '10', name: '김세한', semesterCount: '', tier: '신입', attendances: { '26.9': '9, 18' } },
  { id: '11', name: '김어진', semesterCount: '', tier: '신입', attendances: { '26.9': '8' } },
  { id: '12', name: '김영현', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '' } },
  { id: '13', name: '김예나', semesterCount: '', tier: '신입', attendances: { '26.9': '4, 8, 12(대러리), 15, 20, 22, 27' } },
  { id: '14', name: '김예안', semesterCount: '', tier: '신입', attendances: { '26.9': '1, 11, 12(대러리)' } },
  { id: '15', name: '김용준', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '4, 18' } },
  { id: '16', name: '김우탁', semesterCount: '3', tier: 'OB', attendances: { '26.9': '20' } },
  { id: '17', name: '김재욱', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '' }, inactiveStatus: '군 휴학' },
  { id: '18', name: '김준엽', semesterCount: '2', tier: '정회원_2', attendances: { '26.9': '6(YTN), 8, 12(대러리), 13(춘천), 15, 20, 22' } },
  { id: '19', name: '김지홍', semesterCount: '3+', tier: 'OB', attendances: { '26.9': '10' } },
  { id: '20', name: '김채은', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '21', name: '김희종', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '' } },
  { id: '22', name: '노종현', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '23', name: '류혜빈', semesterCount: '2', tier: '정회원_2', attendances: { '26.9': '5(레드불), 9, 12(대러리), 20' } },
  { id: '24', name: '박건우', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '' }, inactiveStatus: '군 휴학' },
  { id: '25', name: '박수홍', semesterCount: '2', tier: '정회원_2', attendances: { '26.9': '1, 4, 6, 8' } },
  { id: '26', name: '박이안', semesterCount: '', tier: '신입', attendances: { '26.9': '4, 5(레드불), 6, 8, 9, 11, 12(대러리), 13' } },
  { id: '27', name: '박이현', semesterCount: '', tier: '신입', attendances: { '26.9': '8, 15, 18' } },
  { id: '28', name: '박재혁', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '29', name: '박종혁', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '30', name: '배소이', semesterCount: '', tier: '신입', attendances: { '26.9': '8, 15' } },
  { id: '31', name: '배현호', semesterCount: '', tier: '신입', attendances: { '26.9': '8, 22' } },
  { id: '32', name: '성우진', semesterCount: '', tier: '신입', attendances: { '26.9': '1' } },
  { id: '33', name: '신동훈', semesterCount: '3', tier: 'OB', attendances: { '26.9': '5(레드불), 6' } },
  { id: '34', name: '심예영', semesterCount: '', tier: '신입', attendances: { '26.9': '18' } },
  { id: '35', name: '안태현', semesterCount: '', tier: '신입', attendances: { '26.9': '1, 8' } },
  { id: '36', name: '어민준', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '37', name: '염원준', semesterCount: '2', tier: '정회원_2', attendances: { '26.9': '' } },
  { id: '38', name: '유동현', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '' } },
  { id: '39', name: '유지훈', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '1, 2, 4, 5(레드불), 6, 8, 9, 10, 11, 12(대러리), 13, 15, 17, 18, 20, 22, 27' } },
  { id: '40', name: '이상혁', semesterCount: '3+', tier: 'OB', attendances: { '26.9': '4, 5(레드불)' } },
  { id: '41', name: '이서현', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '42', name: '이영수', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '43', name: '이용권', semesterCount: '2', tier: '정회원_2', attendances: { '26.9': '9, 17' } },
  { id: '44', name: '이우성', semesterCount: '', tier: '신입', attendances: { '26.9': '18' } },
  { id: '45', name: '이재헌', semesterCount: '2', tier: '정회원_2', attendances: { '26.9': '2, 4, 8, 9, 13(춘천)' }, note: '페널티 지급' },
  { id: '46', name: '이재호', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '47', name: '이주호', semesterCount: '', tier: '신입', attendances: { '26.9': '15' } },
  { id: '48', name: '이준아', semesterCount: '', tier: '신입', attendances: { '26.9': '15' } },
  { id: '49', name: '임민아', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '' } },
  { id: '50', name: '장우혁', semesterCount: '', tier: '신입', attendances: { '26.9': '6' } },
  { id: '51', name: '장지원', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '52', name: '전용학', semesterCount: '', tier: '신입', attendances: { '26.9': '15' } },
  { id: '53', name: '전풍', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '54', name: '정동호', semesterCount: '3+', tier: 'OB', attendances: { '26.9': '' } },
  { id: '55', name: '정지훈', semesterCount: '', tier: '신입', attendances: { '26.9': '4, 8, 9, 11, 12(대러리), 15, 18' } },
  { id: '56', name: '정진우', semesterCount: '', tier: '신입', attendances: { '26.9': '15' } },
  { id: '57', name: '조서윤', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '58', name: '조영채', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '59', name: '조형준', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '' } },
  { id: '60', name: '천중헌', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '8, 15' } },
  { id: '61', name: '최윤서', semesterCount: '', tier: '신입', attendances: { '26.9': '4, 6, 8, 12(대러리), 18' } },
  { id: '62', name: '최은서', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '63', name: '최지혁', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '64', name: '최현서', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '' } },
  { id: '65', name: '한지헌', semesterCount: '', tier: '신입', attendances: { '26.9': '' } },
  { id: '66', name: '한희재', semesterCount: '', tier: '신입', attendances: { '26.9': '1, 8, 18, 22, 27' } },
  { id: '67', name: '허동형', semesterCount: '', tier: '신입', attendances: { '26.9': '15' } },
  { id: '68', name: '허혜진', semesterCount: '', tier: '신입', attendances: { '26.9': '4' } },
  { id: '69', name: '현준우', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '15' } },
  { id: '70', name: '홍노아', semesterCount: '1', tier: '정회원_1', attendances: { '26.9': '' } },
  { id: '71', name: '홍민석', semesterCount: '', tier: '신입', attendances: { '26.9': '18' } },
  { id: '72', name: '홍새누', semesterCount: '', tier: '신입', attendances: { '26.9': '15, 18' } },
  { id: '73', name: '홍유진', semesterCount: '3+', tier: 'OB', attendances: { '26.9': '' }, inactiveStatus: '비활동' },
  { id: '74', name: '홍윤표', semesterCount: '3', tier: 'OB', attendances: { '26.9': '' } },
  { id: '75', name: '황석환', semesterCount: '3+', tier: 'OB', attendances: { '26.9': '2, 6(YTN), 8, 9' } },
];
